### ISSUE TITLE
Windows UBFG-1.1 download problem

### ISSUE THREAD

**Issue by ApcIvanov47** [scriptum/UBFG#10]
This link http://dl.dropbox.com/u/59878867/UBFG-1.1.exe on Wiki\Downloads page returns 403 error.

**Comment by scriptum** [comment]
Unfortunately Dropbox silently deactivated my account. I'm trying to contact with support.

**Comment by Saxmax** [comment]
The link to download still does not work. :/
Could you put it back up, and if Dropbox doesn't work maybe use another site for hosting the tool? :)

**Comment by masagrator** [comment]
[UBFG-1.1.zip](https://github.com/scriptum/UBFG/files/7741091/UBFG-1.1.zip)

Sadly this tool didn't met my expectations.
