### ISSUE TITLE
Latest OSX build

### ISSUE THREAD

**Issue by ppiecuch** [scriptum/UBFG#2]
Hello
Here it is: http://code.google.com/p/ppiecuch-projects/downloads/detail?name=UBFG-04092012.zip

Do you have any plans for Distance Field feature?

Regards
Pawel

**Comment by scriptum** [comment]
Hello! Thanks for building, DF is planned but not yet implemented.

**Comment by scriptum** [comment]
Updated: added DF feature, also see new Mac OS build: https://github.com/scriptum/UBFG/wiki/Downloads
