### ISSUE TITLE
Mac OS 10.8.2: Crashing on launch

### ISSUE THREAD

**Issue by adolgoff** [scriptum/UBFG#4]
Process:         UBFG [72181]
Path:            /Users/USER/Desktop/UBFG.app/Contents/MacOS/UBFG
Identifier:      com.yourcompany.UBFG
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [343]
User ID:         501

Date/Time:       2013-02-27 15:13:11.740 +0400
OS Version:      Mac OS X 10.8.2 (12C60)
Report Version:  10

Interval Since Last Report:          49864 sec
Crashes Since Last Report:           4
Per-App Crashes Since Last Report:   1
Anonymous UUID:                      0559A711-6487-7F7D-9E2C-3BF89FADD16B

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: QtGui.framework/Versions/4/QtGui
  Referenced from: /Users/USER/Desktop/UBFG.app/Contents/MacOS/UBFG
  Reason: image not found

Binary Images:
       0x100000000 -        0x100049ff7 +com.yourcompany.UBFG (???) <4F61C809-0879-341C-8704-9C43B8743D22> /Users/USER/Desktop/UBFG.app/Contents/MacOS/UBFG
    0x7fff63a73000 -     0x7fff63aa793f  dyld (210.2.3) <A40597AA-5529-3337-8C09-D8A014EB1578> /usr/lib/dyld

Model: MacBookPro5,5, BootROM MBP55.00AC.B03, 2 processors, Intel Core 2 Duo, 2.26 GHz, 8 GB, SMC 1.47f2
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x802C, 0x31364A53463531323634485A2D3147314431
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x802C, 0x31364A53463531323634485A2D3147314431
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.81.22)
Bluetooth: Version 4.0.9f33 10885, 2 service, 18 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: OCZ-PETROL, 256,06 GB
Serial ATA Device: HL-DT-ST DVDRW  GS23N
USB Device: Internal Memory Card Reader, apple_vendor_id, 0x8403, 0x26500000 / 2
USB Device: Built-in iSight, apple_vendor_id, 0x8507, 0x24400000 / 2
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x06100000 / 2
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8213, 0x06110000 / 5
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0236, 0x04600000 / 3
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0x04500000 / 2

**Comment by bazhenovc** [comment]
No Qt installed?

**Comment by adolgoff** [comment]
For that moment – no idea. Does it cause crashes?

**Comment by bazhenovc** [comment]
Yes, I think that you need to install Qt libraries, here is the link: http://download.qt-project.org/official_releases/qt/4.8/4.8.4/qt-mac-opensource-4.8.4.dmg

**Comment by adolgoff** [comment]
Thank you, I don't remember how I did solve my issue, but anyway it could be useful for another time!
